### Тема “Вычисления с помощью Numpy”

In [60]:
import numpy as np

#### Задание 1
#### Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [61]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [62]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

#### Задание 2
#### Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [63]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание 3
#### Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp.

In [64]:
a1 = a_centered[:,0] # все значения из первого столбца массива a_centered
a2 = a_centered[:,1] # двоеточчие - это срез

# a_centered_sp = np.dot(a1, a2)
a_centered_sp = a1 @ a2
a_centered_sp

8.0

#### Затем поделите a_centered_sp на N-1, где N - число наблюдений

In [65]:
N = a.shape[0] # размер измерения в массиве [кол-во строк]
N

5

In [66]:
my_cov = a_centered_sp / (N - 1)
my_cov

2.0

#### Задание 4**
#### Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.

#### В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1. 1.
1.

In [67]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

### Тема “Работа с данными в Pandas”

In [68]:
import pandas as pd

#### Задание 1
#### Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
#### Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:
#### [1, 1, 1, 2, 2, 3, 3],
#### ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']
#### Нужны prices!
#### [500, 400, 300, 350, 450, 600, 200]

In [69]:
authors = pd.DataFrame({'author_id': [1, 2, 3], 
                        'author_name': ['Тургенев', 'Чехов', 'Островский']}, columns=['author_id', 'author_name'])

# Устанавливаем новые индексы вместо столбца индексов
# authors = authors.set_index('author_id')

print(authors)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский


In [70]:
data_2 = {'author_id': [1, 1, 1, 2, 2, 3, 3], 
          'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
          'price': [500, 400, 300, 350, 450, 600, 200]}
books = pd.DataFrame(data_2)

print(books)

   author_id            book_title  price
0          1           Отцы и дети    500
1          1                 Рудин    400
2          1     Дворянское гнездо    300
3          2      Толстый и тонкий    350
4          2       Дама с собачкой    450
5          3                 Гроза    600
6          3  Таланты и поклонники    200


#### Задание 2
#### Получите датафрейм authors_price, соединив дата фреймы authors и books по полю author_id.

In [71]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'outer')
# 'outer': использовать объединение ключей из обоих фреймов, аналогично full outer join (полное внешнее соединение) в SQL
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    500
1          1    Тургенев                 Рудин    400
2          1    Тургенев     Дворянское гнездо    300
3          2       Чехов      Толстый и тонкий    350
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    600
6          3  Островский  Таланты и поклонники    200

#### Задание 3
#### Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [72]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name        book_title  price
5          3  Островский             Гроза    600
0          1    Тургенев       Отцы и дети    500
4          2       Чехов   Дама с собачкой    450
1          1    Тургенев             Рудин    400
3          2       Чехов  Толстый и тонкий    350

#### Задание 4
#### Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца: 
#### author_name, min_price, max_price и mean_price, в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [73]:
# Группируем данные по имени автора и вычисляем необходимые статистики
authors_stat = authors_price.groupby('author_name').agg( # Группируем данные по столбцу `author_name`
    # агренированные значения из столбца `price` - полученные каким-то образом из групп других значений
    min_price = ('price', 'min'),
    max_price = ('price', 'max'),
    mean_price = ('price', 'mean')
).reset_index()
print(authors_stat)

  author_name  min_price  max_price  mean_price
0  Островский        200        600       400.0
1    Тургенев        300        500       400.0
2       Чехов        350        450       400.0


#### Задание 5**
#### Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка: ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

In [74]:
authors_cover = authors_price.assign(cover = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'])
authors_cover

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    500  твердая
1          1    Тургенев                 Рудин    400   мягкая
2          1    Тургенев     Дворянское гнездо    300   мягкая
3          2       Чехов      Толстый и тонкий    350  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    600   мягкая
6          3  Островский  Таланты и поклонники    200   мягкая

#### Просмотрите документацию по функции pd.pivot table с помощью вопросительного знака. 

In [75]:
# pd.pivot_table?
help(pd.pivot_table)

Help on function pivot_table in module pandas.core.reshape.pivot:

pivot_table(data: 'DataFrame', values=None, index=None, columns=None, aggfunc: 'AggFuncType' = 'mean', fill_value=None, margins: 'bool' = False, dropna: 'bool' = True, margins_name: 'Hashable' = 'All', observed: 'bool | lib.NoDefault' = <no_default>, sort: 'bool' = True) -> 'DataFrame'
    Create a spreadsheet-style pivot table as a DataFrame.
    
    The levels in the pivot table will be stored in MultiIndex objects
    (hierarchical indexes) on the index and columns of the result DataFrame.
    
    Parameters
    ----------
    data : DataFrame
    values : list-like or scalar, optional
        Column or columns to aggregate.
    index : column, Grouper, array, or list of the previous
        Keys to group by on the pivot table index. If a list is passed,
        it can contain any of the other types (except list). If an array is
        passed, it must be the same length as the data and will be used in
        the 

#### Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.

In [76]:
# Создание сводной таблицы
book_info = pd.pivot_table(authors_cover, 
                             values='price', 
                             index='author_name', 
                             columns='cover', 
                             aggfunc='sum', # # Используем строку 'sum' вместо np.sum, чтобы не было предупреждения
                             fill_value=0)

# Переименование столбцов
book_info.columns.name = None
book_info = book_info.rename(columns={'твердая': 'твердая', 'мягкая': 'мягкая'})

print(book_info)

             мягкая  твердая
author_name                 
Островский      800        0
Тургенев        700      500
Чехов             0      800


#### Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [77]:
# Сохранение в формат pickle
book_info.to_pickle('book_info.pkl')

In [78]:
# Загрузка из файла pickle
book_info2 = pd.read_pickle('book_info.pkl')

In [79]:
# Проверка идентичности датафреймов
print(book_info.equals(book_info2))  # Должно вывести True

True
